# All attributes must be valid and are required at the same time.

cds_path: '/home/amohs002/projects/research/FUGUE/my_data/saccharomyces_cerevisiae_cds.fna'
proteome_path: '/home/amohs002/projects/research/FUGUE/my_data/proteomes/saccharomyces_cerevisiae.faa'

query_proteins_dir: '/home/amohs002/projects/research/FUGUE/data/fourdbs_concat/proteomes/'

species: 'saccharomyces_cerevisiae'  # reference species
gene_names: ['LYS2', 'TRP1', 'URA3', 'FCY1', 'GAP1', 'CAN1']